apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-v2
  labels:   #两个标签被附加到pod上
    creation_method: manual
    env: prod
spec:
  containers:
  - image: luksa/kubia
    name: kubia
    ports:
    - containerPort: 8080
      protocol: TCP
